### PR TITLE
Installed the config files.

### PR DESCRIPTION
**Pull request by tonybaltovski**

### CODE REVIEW

**Comment by tonybaltovski** [comment]
@mikepurvis might I trouble you for a release, please?

**Comment by mikepurvis** [comment]
Can you investigate the test failure, please?

http://build.ros.org/job/Kdev__interactive_marker_twist_server__ubuntu_xenial_amd64/changes

**Comment by mikepurvis** [comment]
Release done:

https://github.com/ros/rosdistro/pull/15340
https://github.com/ros/rosdistro/pull/15347

**Comment by tonybaltovski** [comment]
Wonderful! Lunar too!

**Pull request merged**
